name: template_provider_mvvm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity_plus: ^3.0.2
  device_info: ^2.0.3
  device_preview: ^1.1.0
  dio: ^4.0.6
  file_picker: ^5.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.10
  firebase_performance: ^0.9.0+10
  flutter_advanced_drawer: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.3
  heic_to_jpg: ^0.2.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  logger: ^1.1.0
  modal_progress_hud_nsn: ^0.3.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.5
  firebase_messaging_platform_interface: ^4.2.10
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  rename: ^2.1.1
  # flutter pub global run rename --bundleId com.onatcipli.networkUpp
  # flutter pub global run rename --appname "Network Upp"
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo3.jpg"
  # How to use : flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - assets/